### ISSUE TITLE
Dependency on external libsbml causes segfault on Mac

### ISSUE THREAD

**Issue by 0u812** [sys-bio/libsbml-draw#1]
When an external libsbml is imported, it can cause conflicts with the version of libsbml that is statically linked with libsbml-draw.

Line 8 of the file [src/python/libsbml_draw/model/sbml_layout.py](https://github.com/sys-bio/libsbml-draw/blob/master/src/python/libsbml_draw/model/sbml_layout.py#L8) contains:
```python
import libsbml
```

In order to fix the segfault, all references to libsbml need to be removed.
If you need to call libsbml functions, please expose them via libsbml-draw.

**Comment by nrhawkins** [comment]
We're still relying on libsbml python.  We no longer have the seg fault on mac.
