### ISSUE TITLE
Font size and colors reset after call to regenerateLayoutAndNetwork()

### ISSUE THREAD

**Issue by hsauro** [sys-bio/libsbml-draw#10]
When I used the following code:

s.setNodeFontSize('all', 15)
s.setReactionCurveWidth ('all', 3)
s.setNodeColor('all', 'red')
s.setNodeFontColor ('all', 'white')
s.drawNetwork(figure_size=(12,12))

s.regenerateLayoutAndNetwork()
s.drawNetwork(figure_size=(12,12))

I notice that font and color settings are reset after a call to s.regenerateLayoutAndNetwork(). Question is, is this the best behavior? Should settings be preserved between calls of s.regenerateLayoutAndNetwork()?

What does regenerate the layout and network mean? What's the difference between the layout and the network? Would it be possible to just have a regenerateLayout call?

**Comment by nrhawkins** [comment]
It should be possible.  I'll look into it.

**Comment by nrhawkins** [comment]
I added this feature as a new method in SBMLlayout, regenerateLayout()
