### ISSUE TITLE
Too much white space and names not fitting into nodes

### ISSUE THREAD

**Issue by hsauro** [sys-bio/libsbml-draw#12]
Consider the following code, the output has a lot of white space around the image and the nodes are overflowing the node widths (See enclosed image). Cna we reduce the amount of white space and make sure that test is always within the node boundaries.  This should be done internally by changing the node widths rather than the font size since the font size will be set by the user. 

import tellurium as te
import libsbml_draw as SBMLlayout

r = te.loada('''
  // Reactions:
  J0: Node8_Long_Name + Node5 => Node9; J0_k*Node8_Long_Name*Node5;
  J1: Node11 + Node9 => Node14; J1_k*Node11*Node9;
  J2: Node0 + Node13 => Node7 + Node12; J2_k*Node0*Node13;
  J3: Node0 => Node13; J3_k*Node0;
  J4: Node8_Long_Name + Node14 => Node6; J4_k*Node8_Long_Name*Node14;
  J5: Node12 + Node5 => Node13 + Node0; J5_k*Node12*Node5;
  J6: Node0 + Node3 => Node8_Long_Name; J6_k*Node0*Node3;
  J7: Node10 => Node8_Long_Name; J7_k*Node10;

  // Variable initializations:
  J0_k = 0.1;
  J1_k = 0.1;
  J2_k = 0.1;
  J3_k = 0.1;
  J4_k = 0.1;
  J5_k = 0.1;
  J6_k = 0.1;
  J7_k = 0.1;
''')
    
s = SBMLlayout.SBMLlayout (r.getSBML())
s.setReactionCurveWidth ('all', 1)
p = s.drawNetwork(figure_size=(12,10))

![bugLayout](https://user-images.githubusercontent.com/1054990/57947553-0d96f280-7894-11e9-89e6-031b45d765f8.png)

**Comment by nrhawkins** [comment]
As we have been discussing in the other issues like this one, no test for "node text length vs node box width" is being made here in the current version, because the user has specified a fig size.  The test takes place when figsize is autocomputed.

I suppose the white space is coming from the figsize specified.

**Comment by nrhawkins** [comment]
I switched to a completely new method for "node size".  I am closing this issue.  You can test the new 0.0.7 version and open new issues as appropriate.
