### ISSUE TITLE
WriteSBMLFile only writes out render information

### ISSUE THREAD

**Issue by hsauro** [sys-bio/libsbml-draw#5]
The writeSBMLFile method only writes out render information. There is no layout information in the resulting file. The following code gives a really strange image:

s = SBMLlayout.SBMLlayout ('c:\\tmp\\testlayout.txt')
s.drawNetwork()
s.writeSBMLFile ('c:\\tmp\\l1.xml')

s = SBMLlayout.SBMLlayout ('c:\\tmp\\l1.xml')
s.drawNetwork()

![image](https://user-images.githubusercontent.com/1054990/57238506-66d26c80-6fde-11e9-8ce5-f9686beca022.png)
[testLayout.txt](https://github.com/sys-bio/libsbml-draw/files/3148814/testLayout.txt)

**Comment by nrhawkins** [comment]
The SBNW code did not support level 2 files.  We adjusted the C/C++ code to upconvert level 2 files to level 3.
